bash scripts/evaluate_smh_cooccurrence_threshold.sh experiments/topic_discovery/smh/reuters
bash scripts/evaluate_smh_tuple_size.sh experiments/topic_discovery/smh/reuters
bash scripts/evaluate_smh_vocabulary_size.sh experiments/topic_discovery/smh/reuters
bash scripts/evaluate_smh_weighted.sh experiments/topic_discovery/smh/reuters
bash scripts/evaluate_smh_overlap.sh experiments/topic_discovery/smh/reuters
